-- Optional demo tasks for Supabase.
-- Run after schema.sql if you want the public site to start with the same MVP example tasks.

insert into public.tasks (
  id, title, organization, summary, details, skills, mode, time,
  volunteer_hours, contact, status, location, privacy_consent, created_at
) values
(
  'task-tutoring-reading',
  '線上英語閱讀陪伴小隊',
  '山海學習陪伴計畫',
  '每週一次，在帶班老師全程在線下，陪伴國中生閱讀短篇故事、練習表達並完成討論。',
  '組織會提供閱讀素材、帶領指引與兒少保護培訓。每次活動都有帶班老師共同進行，青年夥伴負責提問、鼓勵與學習紀錄，不需要獨立授課，也不會私下聯絡學生。',
  array['課輔陪伴', '活動支援'],
  '線上',
  '7/08－8/26，每週二 19:00－20:30',
  true,
  'tutoring.read@example.org',
  '招募中',
  '不限地區',
  true,
  '2026-06-22T09:00:00.000Z'
),
(
  'task-tutoring-math',
  '週末數學解題陪伴',
  '社區共學基地',
  '跟著基地老師與既有教材，陪伴國中生練習基礎數學，把「不敢問」變成願意一起找答案。',
  '基地老師會先說明教材進度、分組方式與陪伴界線。青年夥伴在現場督導下協助學生拆解題目、整理錯題與建立學習信心；所有活動都在基地公開空間進行。',
  array['課輔陪伴', '資料整理'],
  '實體',
  '7/12－8/30，隔週六 09:30－12:00',
  true,
  'tutoring.math@example.org',
  '招募中',
  '新北市三重區',
  true,
  '2026-06-21T09:00:00.000Z'
),
(
  'task-story-cards',
  '教育現場故事圖卡設計',
  '偏鄉教育行動聯盟',
  '把第一線教師訪談整理成 6 張易讀社群圖卡，讓更多青年理解教育資源落差不是個人問題。',
  '我們已完成三位第一線教師的匿名訪談逐字稿，希望由青年夥伴協助梳理重點、建立視覺語言並完成一組社群圖卡。任務不會接觸學童，內容發布前會由組織完成隱私與專業審查。',
  array['視覺設計', '社群企劃'],
  '線上',
  '7/01－7/14，約 8 小時',
  true,
  'hello@example.org',
  '招募中',
  '不限地區',
  true,
  '2026-06-18T09:00:00.000Z'
),
(
  'task-video',
  '教育平權 60 秒短片剪輯',
  '青年教育倡議小組',
  '將公開素材剪成一支 60 秒短片，回答「為什麼出生地不該決定學習機會？」',
  '團隊會提供腳本、已授權影像與字幕初稿。期待熟悉 Reels 或 Shorts 節奏的夥伴共同完成剪輯、字幕與簡易動態效果。',
  array['影音剪輯', '社群企劃'],
  '線上',
  '6/28－7/10，約 6 小時',
  true,
  'media@example.org',
  '招募中',
  '不限地區',
  true,
  '2026-06-16T09:00:00.000Z'
),
(
  'task-data',
  '教育資源地圖資料清理',
  '地方學習支持中心',
  '協助整理公開資料，讓偏遠地區課後支持資源更容易被搜尋與更新。',
  '依照既有欄位規則，檢查約 200 筆公開資料的格式、重複值與失效連結，並記錄需要人工確認的項目。適合細心、喜歡試算表或資料工作的夥伴。',
  array['資料整理', '行政協助'],
  '線上',
  '7 月，每週 2 小時，共 4 週',
  true,
  'data@example.org',
  '招募中',
  '不限地區',
  true,
  '2026-06-15T09:00:00.000Z'
),
(
  'task-workshop',
  '青年教育議題工作坊支援',
  '共好高中教師社群',
  '協助一場高中生教育議題工作坊的報到、攝影紀錄與回饋整理。',
  '活動將帶青年從生活經驗理解教育不平等。需要夥伴協助場佈、報到、公開活動攝影與匿名回饋表整理；不涉及教學或個別學童陪伴。',
  array['活動支援', '訪談紀錄'],
  '實體',
  '7/20（日）09:00－16:00',
  true,
  'workshop@example.org',
  '招募中',
  '台北市中正區',
  true,
  '2026-06-13T09:00:00.000Z'
),
(
  'task-website',
  '學習資源頁無障礙健檢',
  '開放教育資源站',
  '檢查行動版閱讀體驗與基本無障礙問題，提出一份可執行的改善清單。',
  '針對現有網站的 5 個核心頁面進行鍵盤操作、對比、文字層級與手機版檢查。可以只做健檢，也歡迎提出小型前端修正。',
  array['網站協助', '視覺設計'],
  '線上',
  '7 月上旬，約 5 小時',
  false,
  'web@example.org',
  '已媒合',
  '不限地區',
  true,
  '2026-06-10T09:00:00.000Z'
),
(
  'task-translate',
  '國際教育案例中文摘要',
  '教育創新資料庫',
  '把 3 篇國際教育公平案例整理為繁體中文重點摘要，供青年讀書會使用。',
  '每篇原文約 1,200 字，需要翻譯重點並以白話整理成 300 字摘要。所有原文均為組織可使用的公開授權內容。',
  array['翻譯', '資料整理'],
  '線上',
  '已於 6/15 完成',
  true,
  'translate@example.org',
  '已結束',
  '不限地區',
  true,
  '2026-06-01T09:00:00.000Z'
)
on conflict (id) do update set
  title = excluded.title,
  organization = excluded.organization,
  summary = excluded.summary,
  details = excluded.details,
  skills = excluded.skills,
  mode = excluded.mode,
  time = excluded.time,
  volunteer_hours = excluded.volunteer_hours,
  contact = excluded.contact,
  status = excluded.status,
  location = excluded.location,
  privacy_consent = excluded.privacy_consent;
